name: squirrelwheelchair
description: A new Flutter project.
publish_to: 'none'
version: 0.0.3+2
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_app_check: ^0.1.4
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  cloud_functions: ^4.3.0
  firebase_storage: ^11.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  go_router: ^7.0.2
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  flutter_markdown: ^0.6.14
  url_launcher: ^6.1.11
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.0
  intl_utils: ^2.8.2
  mockito: ^5.4.0
flutter:
  uses-material-design: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf 
  assets:
    - assets/images/logo-192.png
    - assets/fonts/OFL.txt
    - assets/privacy_policy-en.md
    - assets/privacy_policy-ja.md
    - LICENSE
flutter_intl:
  enabled: true
flutter_native_splash:
  image: "assets/images/logo-invert.png"
  image_dark: "assets/images/logo.png"
  color: "#B0BEC5"
  color_dark: "#546E7A"
