name: squirrelwheelchair
description: A new Flutter project.
publish_to: 'none'
version: 0.0.2+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_app_check: ^0.1.4
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  cloud_functions: ^4.3.0
  firebase_storage: ^11.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl_utils: ^2.8.2
flutter:
  uses-material-design: true
  # assets:
  #   - google_fonts/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
flutter_intl:
  enabled: true
