name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - .github/workflows/firebase-hosting-pull-request.yml
jobs:
  build_and_deploy:
    env:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/service_account.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo NODE_ENV=production > functions/.env
      - name: Create SA key
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}' | base64 -d \
          > $GOOGLE_APPLICATION_CREDENTIALS

      - name: Detect modified source
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            functions:
              - 'functions/**'
            firestore:
              - 'firestore.*'
            storage:
              - 'storage.*'

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache-dependency-path: 'package-lock.json'
      - run: npm ci

      - if: steps.filter.outputs.functions == 'true'
        name: Cache functions/node_modules
        uses: actions/cache@v2
        id: cache-functions-node_modules
        with:
          path: functions/node_modules
          key: ${{ runner.os }}-${{ hashFiles('functions/package-lock.json ') }}
      - if: steps.filter.outputs.functions == 'true'
        name: Test and Deploy Functions
        run: |
          npm ci --prefix functions && \
          npm test --prefix functions && \
          npx firebase deploy --only functions --force
      - if: steps.filter.outputs.firestore == 'true'
        name: Deploy Firestore
        run: npx firebase deploy --only firestore
      - if: steps.filter.outputs.storage == 'true'
        name: Deploy Storage
        run: npx firebase deploy --only storage

      - name: Set firebase api key
        run: |
          sed 's/FIREBASE_API_KEY/${{ secrets.FIREBASE_API_KEY }}/' \
            -i lib/config/firebase_options.dart
      - name: Set UI version
        run: |
          VERSION=`grep 'version:' pubspec.yaml | sed 's/.*\s//'` && \
            sed "s/for\ test/$VERSION/" -i lib/version.dart  && \
            echo "{\"version\":\"$VERSION\"}" > web/version.json && \
            echo $VERSION
      - uses: kuhnroyal/flutter-fvm-config-action@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: ${{ runner.os }}-${{ hashFiles('package-lock.json ') }}
      - run: flutter pub get
      - run: flutter test --coverage
      - run: flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SQUIRRELWHEELCHAIR }}'
          channelId: live
          projectId: squirrelwheelchair
      - name: Trigger system update job
        run: npx firebase firestore:delete service/upgrade --force
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info,./functions/coverage/lcov.info
